### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Joseph-Rance** [Joseph-Rance/Com-Soc-robotic-arm#1]
![image](https://user-images.githubusercontent.com/56409230/94590407-87a7fb80-027e-11eb-9bd5-3d16373fbc62.png)
![image](https://user-images.githubusercontent.com/56409230/94590444-91316380-027e-11eb-94c3-758f82cfa608.png)

**Comment by Joseph-Rance** [comment]
UPDATE 16/10/2020:

I got together a list of parts for the servo power supply, and the components have been sent off. We will be meeting at 6:30 Saturday to discuss the CAD modelling

**Comment by akilan-n2** [comment]
:]

**Comment by Joseph-Rance** [comment]
From the call:
1. ~~What type of Claw to use~~ one finger will bee fixed, the other attached to servo. the stationary finger will be split in two (not too wide though)
2. ~~Best way to attach servos to arm- ie. 3d printed mould, glue, etc~~ Glue in bottom of cup
3. ~~Best way to attach servo axles to next part~~ see pinned diagram; see pinned link for servo connection
4. ~~What type of base (eg should we just stick it to a big piece of mdf)~~ make sheet on bottom go paast servos to put weight on (e.g. book)
5. ~~Best cross section shape~~ needs cad stress testing
6. ~~how to connect the arm to the servo axles~~ see pinned  diagram (3)
7. ~~how to connect the joints~~ see pinned  diagram (3)
8. ~~how to connect that arm together in general~~ see second pinned diagram
10. ~~modularity?~~ use modular fingers (make them easily removable
11. add camera mount to gripper
12. see last pinned diagram for servo locations

**Comment by Joseph-Rance** [comment]
![image](https://user-images.githubusercontent.com/56409230/96606819-99b21280-12ef-11eb-894f-7f290048210e.png)
[link](https://www.amazon.co.uk/Diymore-Digital-Helicopter-Airplane-controls/dp/B07DQFXDC9/ref=pd_lpo_21_t_0/260-2278032-1480546?_encoding=UTF8&pd_rd_i=B07DQFXDC9&pd_rd_r=bcbec4ae-2282-4088-a338-175b3e19b9b4&pd_rd_w=ymRfo&pd_rd_wg=mJinO&pf_rd_p=7b8e3b03-1439-4489-abd4-4a138cf4eca6&pf_rd_r=8KZM3K6MM93SVSGSEP15&psc=1&refRID=8KZM3K6MM93SVSGSEP15)
![image](https://user-images.githubusercontent.com/56409230/96606922-b5b5b400-12ef-11eb-8b8e-f0f4be9e4bc9.png)
6 servos on bottom, 2 on beta, 3 on grabber

**Comment by Joseph-Rance** [comment]
Because we need to make a decision on this and I keep forgetting to bring it up in meetings, I'm just going to make it now: x = 0.4m; y = 0.35m.

**Comment by Joseph-Rance** [comment]
**MESSAGE FROM COM SOC DISCORD**
@BlueScorch2 @[Gwon] @[rebeka] So its going to be us 4 and Hemanth working on the arm.

Mr. McCain mentionned that we have two different 3D printers when we met him at lunch. The filament we are getting is 1.75mm so we'll be using the *flash forge finder* (in case you need any specifications for part size etc.)

I think it will be best if we give each person a specific part to work on. I want to decide what everyone is going to be doing ASAP so if anyone is feeling inspired they can begin already, however we have admissions tests coming up so we'll only properly begin modelling on the week beginning the 9th. I think we should aim to have models complete two weeks after that.

Of course, we will almost certainly meet more problems and decisions, so if there are any issues I'm happy to do a meeting (or dm) to talk about them. Also, we'll have to collaborate a bit to decide how each part will connect to the others, so we need to all meet at some point anyways.

Info for modelling (inc. notes from last meeting) should be here: https://github.com/Joseph-Rance/Com-Soc-robotic-arm/issues/1

If you have a question, that above link may be a good place to ask it so everyone else can see.

With regards to who is doing what, does anyone have any preferences? Also how much each person is willing to do? I imagine we'll split the components up like below:
person 1: alpha hinge + servo holders for alpha
person 2: beta hinge + servo holders for beta
person 3: gamma hinge + servo holders for gamma
person 4: grabber + camera
person 5: x and y beam (+ wire management)

Also, is it possible to get a channel in the eng soc team so we can include Hemanth (and anyone who joins late) in all this?

**Comment by Joseph-Rance** [comment]
Com Soc team todo:
 - [x] Fix rotation finder
 - [x] Begin servo control

**Comment by Joseph-Rance** [comment]
![image](https://user-images.githubusercontent.com/56409230/98451122-d7f66100-213a-11eb-9fd1-154a6e4084af.png)
![image](https://user-images.githubusercontent.com/56409230/98451124-dc227e80-213a-11eb-98ed-097c257134c5.png)

**Comment by Joseph-Rance** [comment]
![Uploading image.png…]()

**Comment by Joseph-Rance** [comment]
![image](https://user-images.githubusercontent.com/56409230/99152833-39b74d80-269c-11eb-98d1-925a5abc85f4.png)

**Comment by Joseph-Rance** [comment]
![image](https://user-images.githubusercontent.com/56409230/99153477-9ddc1080-26a0-11eb-837e-f9401970b123.png)

**Comment by Joseph-Rance** [comment]
servo dimensions: 40x19x43

**Comment by Joseph-Rance** [comment]
Todo before 5pm saturday:
 - [x] Akilan: Base rotation start
 - [x] Gwon: Blue section start
 - [x] Hemanth: Black section start

**Comment by Joseph-Rance** [comment]
Another diagram similar to the ones above
![IMG_20201120_203137](https://user-images.githubusercontent.com/56409230/99847303-cb78fc00-2b6f-11eb-9bb2-e5aa998de3e1.jpg)

**Comment by Joseph-Rance** [comment]
Joe (by next week):
 - [x] Add camera mount to gripper
 - [x] make "wrist" section

Hemanth:
 - [x] start the "elbow section"
 
Gwon:
 - [x] start on base

**Comment by Joseph-Rance** [comment]
gripper and cross section files: [robot arm main.zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/5898469/robot.arm.main.zip)

**Comment by Joseph-Rance** [comment]
If anyone needs the servo layout the most up to date conversation I can find about that on discord has this layout:
1 servo for gripper finger movement
1 servo for gripper rotation
1 servo for gripper up/down
2 servos at "elbow"
6 servos at base for up/down
1 servo for base sideways rotation

**Comment by Joseph-Rance** [comment]
new gripper and x section files: [robot arm main.zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/5899838/robot.arm.main.zip)
badly edited image of them together: 
![image](https://user-images.githubusercontent.com/56409230/106386124-680b1600-63cb-11eb-9ac3-33f6224caa82.png)

**Comment by Joseph-Rance** [comment]
Update: [robot arm main (2).zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/5899904/robot.arm.main.2.zip)
![image](https://user-images.githubusercontent.com/56409230/106387143-44969a00-63d0-11eb-89c0-e8a2083e33a3.png)

**Comment by GwonWorks** [comment]
[BaseGears1.zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/5937386/BaseGears1.zip)
![image](https://user-images.githubusercontent.com/65285511/107126420-b4f95b80-68a7-11eb-8d31-29d7cd1bb9ca.png)

**Comment by Joseph-Rance** [comment]
[robot arm main.zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/5937425/robot.arm.main.zip)

**Comment by Joseph-Rance** [comment]
> Update: [robot arm main (2).zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/5899904/robot.arm.main.2.zip)
> [image](https://user-images.githubusercontent.com/56409230/106387143-44969a00-63d0-11eb-89c0-e8a2083e33a3.png)

I just realised that the rightmost servo here needs to be facing the left

**Comment by Joseph-Rance** [comment]
![Picture1](https://user-images.githubusercontent.com/56409230/107159396-979bbe80-6987-11eb-978f-f5cb7d65c504.png)
[robot arm main (2).zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/5939990/robot.arm.main.2.zip)

Edit: the cylinder on the right needs to be rotated 90 degrees

**Comment by GwonWorks** [comment]
[BaseGears2.zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/5978175/BaseGears2.zip)

![image](https://user-images.githubusercontent.com/65285511/107884384-ad136a00-6eec-11eb-917e-bf87d12f703e.png)
Added a hold with top diameter = 21mm (depth 7mm) and bottom diameter = 32mm (sloped)

**Comment by GwonWorks** [comment]
Does this update live?

**Comment by Joseph-Rance** [comment]
- [x] Joe: Make y part of the elbow
 - [ ] Hemanth: Make x part of the elbow:
![image](https://user-images.githubusercontent.com/56409230/107885084-1a74ca00-6ef0-11eb-9366-29e54deed6c6.png)
inner circle diameter is 25mm
distance between servos is 25mm
 - [x] Gwon: Make bit for x arm to rest on (+ remove connection to base of servo)
 - [x] Akilan: 
![image](https://user-images.githubusercontent.com/56409230/107885107-4d1ec280-6ef0-11eb-80d2-ec08fecfecd7.png)

Akilan and Hemanth: make your x section end in I shape

Files: 
[robot arm main (3).zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/5978217/robot.arm.main.3.zip)

**Comment by Joseph-Rance** [comment]
left to do:
 - make connections to servos

**Comment by Joseph-Rance** [comment]
changes to beta/elbow/xy joint:
![image](https://user-images.githubusercontent.com/56409230/107984377-bae5ef80-6fbf-11eb-965e-7be2e1c3eab1.png)
[updated models.zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/5983556/updated.models.zip)

**Comment by akilan-n2** [comment]
![image](https://user-images.githubusercontent.com/65403906/107990727-f6d38180-6fcc-11eb-8153-4c822fb4a54f.png)
[bullet bill.zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/5983988/bullet.bill.zip)
(>'-')>

**Comment by GwonWorks** [comment]
[BaseArmHolder.zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/6018130/BaseArmHolder.zip)
![image](https://user-images.githubusercontent.com/65285511/108632651-fec97080-7467-11eb-8859-577bce6d5ef4.png)

**Comment by Joseph-Rance** [comment]
[cad.zip](https://github.com/Joseph-Rance/Com-Soc-robotic-arm/files/6018229/cad.zip)
![image](https://user-images.githubusercontent.com/56409230/108634365-28d36080-7471-11eb-99cc-b2a505ba4dca.png)

**Comment by Joseph-Rance** [comment]
![image](https://user-images.githubusercontent.com/56409230/108692556-aab89d80-74f4-11eb-98aa-387e124251ea.png)

**Comment by Joseph-Rance** [comment]
5.85 mm diameter spline

**Comment by Joseph-Rance** [comment]
![image](https://user-images.githubusercontent.com/56409230/121247255-f0c62100-c899-11eb-98d9-498dca9ad8e9.png)

**Comment by Joseph-Rance** [comment]
https://www.amazon.co.uk/gp/product/B07FY2T89M/
